[package]
name = "tokio-graceful-shutdown"
authors = ["Finomnis <finomnis@gmail.com>"]
version = "0.1.3"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/Finomnis/tokio-graceful-shutdown"
description = "Utilities to perform a graceful shutdown on a Tokio based system."
keywords = ["tokio", "shutdown"]
categories = ["asynchronous"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
    "/.github/"
]

[dependencies]
# Result propagation. TODO remove?
anyhow = "1.0"

# For holding the shutdown token
lazy_static = "1.4"

# For providing the shutdown token
tokio = { version = "1", default-features = false, features = ["signal", "rt", "macros"] }
tokio-util = { version = "0.6", default-features = false }

# For logging
log = "0.4"


[dev-dependencies]
# Logging
env_logger = "0.9"

# Tokio
tokio = { version = "1", features = ["full"] }
