name: Coverage
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Coverage
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    env:
      RUST_TEST_THREADS: "1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate code coverage
        run: |
          cargo tarpaulin --all-features --workspace --timeout 120 --out Lcov

      - name: Upload to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.github_token }}
